import Footer from './components/footer/Footer'
import Header from './components/header/Header'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Foodhunter by Sumin, Teayeon',
  description: 'Generated by create next app with by Sumin, Teayeon ',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
